### ISSUE TITLE
Could not find the following dependencies: mysqladmin rsync

### ISSUE THREAD

**Issue by wuhui3344** [MagePsycho/magento2-installer-bash-script#1]
✖ root@racknerd-e9ebdf:~# m2-installer --version=2.4.3 --base-url=yang.com --install-sample-data --db-user=magento --db-pass=7z7wiGJMWZGiYz4T --db-name=magento --install-dir=/www/wwwroot/yang.com
✖ Could not find the following dependencies: mysqladmin rsync

Could not find the following dependencies: mysqladmin rsync

**Comment by MagePsycho** [comment]
@wuhui3344 Please check out the latest code. The dependencies on `mysqladmin`  and `rsync` has been removed.
